### ISSUE TITLE
NHL 96 and NHL 2K Files

### ISSUE THREAD

**Issue by jlnhlfan** [wattostudios/GameExtractor#18]
So, someone on the NHL 94 forums wants to mod NHL 96 for DOS by adding more cards and player portraits to the menus. The .viv files containing those very graphics are contained in this zip file.

[VIV.zip](https://github.com/wattostudios/GameExtractor/files/14475632/VIV.zip)

Also, I had the idea of trying to mod NHL 2K on the Dreamcast, but I can't modify the databases. I'd also like to see if I could modify the .cmn files in the game. The files here are for the front-end players and rosters (inside DB.zip), as well as the backgrounds, front-end portraits, in-game faces, and uniforms (inside CMN.zip)

[CMN.zip](https://github.com/wattostudios/GameExtractor/files/14475546/CMN.zip)
[DB.zip](https://github.com/wattostudios/GameExtractor/files/14475547/DB.zip)

If I can get support for these files, I'll be glad. :)

**Comment by jlnhlfan** [comment]
Hello?

**Comment by wattostudios** [comment]
We were able to add read and write support for some of the NHL 96 archives/images, but not all of them. We were able to add support for FEPLAYER.DB from NHL 2k (Dreamcast), but for this one, because it's a standalone file instead of being in an archive, you'll need to add it to a New archive and then double-click to preview/edit it. The first steps of the _"Previewing and Converting Image Files on your PC.pdf"_ tutorial describe this process.

These changes will be in the next public release of Game Extractor, or you can contact me if you require it prior to that.
