### ISSUE TITLE
Support for Outrun 2006: Coast 2 Coast *.pak archives

### ISSUE THREAD

**Issue by ksdomino** [wattostudios/GameExtractor#20]
I tried to extract Englishc_ham_1a.pak sound file from Outrun 2 Coast to Coast.
Game Extractor told me I'd need QuickBMS so I tried to get it to auto download that but that failed so I manually installed QuickBMS and pointed Game extractor, then tried to extract the file but it said no plugins were able to extract the file. 

I've attached the file. Please help if you can. 

[file.zip](https://github.com/user-attachments/files/16162746/file.zip)

**Comment by ksdomino** [comment]
Never mind, I was able to import the file into audacity. Turns out it is just a raw wav file at 11025Hz.

**Comment by wattostudios** [comment]
Apologies for the issue - the fact that it was requesting QuickBMS means it was _trying_ to open the file using a plugin that has a QuickBMS requirement, usually for an unusual compression. As you found out though, this was because the game isn't supported by Game Extractor, and as you say, isn't even an archive, it's just a raw audio file. We wouldn't normally expect Game Extractor to ask for QuickBMS for any archive that's supported (unless it's a game that actually needs it).

We're glad that you managed to figure out the format and get something useful.

**Comment by ksdomino** [comment]
I can open the file and export it out and it works ingame but if I make any changes (even minor volume fixes) then the game crashes. Any ideas?

**Comment by wattostudios** [comment]
From our investigation of these PAK files, it looks to us like they may still be archives. In the file you sent, it seems to contain 22 separate audio files in it, with very small headers between each, which is why perhaps Audacity doesn't even notice the slight headers.

We have written a plugin for this PAK format, including the ability to replace files in the archive. Could you please reach out to us via email at watto@watto.org so we can send you a development build for testing. We _think_ the edited files should work in the game, but will need to work with you to verify it.

**Comment by ksdomino** [comment]
Amazing, Thanks so much and am very much looking forward to testing the development build! I emailed yesterday but just in case it went into the junk box or ether: my email address is ksdominant@gmail.com (ksdominant at gmail dot com in case the system blocks it)

Thanks again and best regards.

**Comment by ksdomino** [comment]
Excellent Start, Thanks so much for adding support for this game!
I managed to do a lot of testing and managed to open _most_ of the archives but there were some that had a few issues. I have attached the files that I was unable to extract.

Thanks again for your continued support with this.
[1 - Problematic Files.zip](https://github.com/user-attachments/files/16244525/1.-.Problematic.Files.zip)

**Comment by wattostudios** [comment]
Thanks for your help, we have now pushed the code for Outrun 2006.

The Problematic Files, as you called them, are a result of Game Extractor choosing the wrong PAK plugin for reading those particular archives - unfortunately PAK files are very common in games, so it can be quite difficult to auto-detect the correct format. You can resolve this by choosing "**Outrun 2006**" or "**PAK_72**" as the file type, at the bottom of the Open Archive window, or in the next release of Game Extractor, we will have code to adjust some of the "false positives" in the auto-detect function, so this shouldn't occur in the future.

If anyone wants this plugin before the next release, you can add the attached **Plugin_PAK_72.class** file into the **GameExtractor.jar** archive in the folder **org\watto\ge\plugin\archive** , or you can contact us via our website and we will be happy to provide you a development build.

[Plugin_PAK_72.zip](https://github.com/user-attachments/files/16248468/Plugin_PAK_72.zip)
