### ISSUE TITLE
Support for The Mummy PC .LBS file extension

### ISSUE THREAD

**Issue by Mrblubb** [wattostudios/GameExtractor#21]
The mummy has zone.lbs & pstart.dat files that should contain 3d models and other stuff. Support for extracting it would be awesome.

**Comment by wattostudios** [comment]
We are always happy to investigate other games, to see whether they can be supported by Game Extractor. Could you please send us an email at watto@watto.org so we can assist you. Thanks.

**Comment by wattostudios** [comment]
We were able to get some of the files you asked about, but as far as we can tell, these aren't archives, they look more like a proprietary level format (which varies for basically every game engine that exists). 

The files are very small - less than half a MB in size, so they don't contain much - they certainly don't contain any images, they just seem to point to other texture files that exist in the game (in the bmps directories).

While you're _probably_ correct that they contain a portion of the 3D models for each level, it isn't in a format that we recognize (we are only new to 3D modelling, so it could still contain 3D model data in there somewhere, but it's something that someone with more expertise in 3D would be able to help with more than us.). We;re going to suggest to ask at some other places, like https://reshax.com/ as there are people there who understand these kinds of files better than us.

We're going to close this issue, primarily because we couldn't find anything "archive-related" in these formats.

**Comment by Mrblubb** [comment]
This really helps. I have a direction now where to look for it. You guys
are doing fantastic service to preserve golden games. Thank you so
much!! 😁👍
